app1:
  build: ./python_app/
  links:
    - "consul1:consul1"
  ports:
    - "8080:8080"
consul1:
  image: "progrium/consul:latest"
  name: "consul1"
  hostname: "consul1"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53"
  command: "-server -bootstrap-expect 3 -ui-dir /ui"
consul2:
  image: "progrium/consul:latest"
  name: "consul2"
  hostname: "consul2"
  ports:
    - "8400"
    - "8500"
    - "8600"
  links:
    - "consul1:consul1"
    - app1
  command: "-server -join consul1"
consul3:
  image: "progrium/consul:latest"
  name: "consul3"
  hostname: "consul3"
  ports:
    - "8400"
    - "8500"
    - "8600"
  links:
    - "consul1:consul1"
    - app1
  command: "-server -join consul1"
